### ISSUE TITLE
Create Notification Pop-Up for No Internet Connection

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Swift#43]
### Tasks
- [x] Design a pop-up with a notification message informing the user about the lack of internet connection.
- [x] Implement connection detection logic to identify when there is no internet.
- [x] Add functionality to automatically display the pop-up when a connection loss is detected.
- [x] Include a "Try Again" button to allow the user to retry the action once the connection is restored.
- [x] Test the pop-up in various disconnection scenarios (e.g., airplane mode, Wi-Fi loss, etc.).

**Comment by eduardoh27** [comment]
The popup is working correctly

**Comment by eduardoh27** [comment]
The popup is working correctly
